config/routes.rb
Rails.application.routes.draw do

   #ネームスペースadminsのルート制御
  namespace :admins do
    resources :events
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #ネームスペースpublicsのルート制御
  #devise_for :users, controllers: {
  #  sessions: 'publics/users/sessions',
  #  registrations: 'publics/users/registrations',
  #  passwords: 'publics/users/passwords'
  #}
  

  #deviseはnamespaceで記載しない、階層を定義したらscopeで定義すること
  
  scope '/publics' do
     devise_for :users, controllers: {
      #各usersフォルダ内のコントローラ指定
      sessions: 'publics/users/sessions',
      registrations: 'publics/users/registrations',
      passwords: 'publics/users/passwords'
    }   
  end
  #scope module: :XXXXX 定義することでURLでXXXXXの部分をpath表示しなくてすむ
  scope module: :publics do
    resources :users, only:[:show,:edit,:update]
    
    resources :events, only:[:index, :show, :new, :edit, :create, :update] do
      collection do
        #新たにeventコントローラに検索(search)アクションを追加
        get 'search' => 'events#search'
      end
      resource :favorites, only:[:create, :destroy]
      resources :event_comments, only: [:create, :destroy]
    end
  end
  
  #devise_scope :user do
  #  get 'publics/users/sign_up', to: 'publics/users/registrations#new'
  #  post 'publics/users/sign_up', to: 'publics/users/registrations#create', as: :publics_user_registration
  #end
  #post 'publics/users' => 'publics/registrations#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to:'homes#top'
    
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/event.rb
class Event < ApplicationRecord
    #belongs_to :user
    
    attachment :image
    has_many :favorites, dependent: :destroy
    has_many :event_comments, dependent: :destroy
    validates :eventname, presence: true, length: { maximum: 20 }
    validates :address, presence: true, length: { maximum: 50 }
    validates :comment, presence: true, length: { maximum: 100 }
    validates :siteurl, presence: true, format: /\A#{URI::regexp(%w(http https))}\z/
    validates :image, presence: true
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
  def self.looks(searches, words)
    if searches == "perfect_match"
      @event = Event.where("eventname LIKE ?", "#{words}")
    elsif searches == "start_match"
      @event = Event.where("eventname LIKE ?", "#{words}%")
    elsif searches == "back_match"
      @event = Event.where("eventname LIKE ?", "%#{words}")
    else
      @event = Event.where("eventname LIKE ?", "%#{words}%")
    end
  end
end

app/controllers/admins/events_controller.rb
class Admins::EventsController < ApplicationController
    #イベント会場一覧
    def index
        #Events = Event.page(params[:page]) カミナリを使用する際はこちら
        @events = Event.all
    end
    #イベント会場登録
    def new
        @event = Event.new
    end
    #イベント会場詳細
    def show
        @event = Event.find(params[:id])
    end
    #イベント会場編集
    def edit
        @event = Event.find(params[:id])
    end
    #イベント会場登録処理
    def create
        @event = Event.new(event_params)
        @event.save
        redirect_to admins_event_path(@event)
    end
    #イベント会場編集処理
    def update
        @event = Event.find(params[:id])
        @event.update(event_params)
        redirect_to admins_event_path(@event)
    end
    #イベント会場削除処理
    def destroy
    
    end
    private
    def event_params
        params.require(:event).permit(:image, :eventname, :address, :siteurl, :comment)
    end
end

app/controllers/publics/event_comments_controller.rb
class Publics::EventCommentsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    comment = current_user.event_comments.new({eventcomment: params[:eventcomment]})
    comment.event_id = @event.id
    comment.save
    #redirect_to request.referer
  end
  
  def destroy
    @comment = EventComment.find(params[:id])
    @event = @comment.event
    @comment.destroy
    #redirect_to request.referer
  end
  
  private
  #def event_comment_params
    #binding.pry
    #params.require(:event_comment).permit(:eventcomment)
  #end
end

app/controllers/publics/events_controller.rb
class Publics::EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update]
    
    #イベント会場一覧
    def index
      @events = Event.page(params[:page]).reverse_order
    end
    
    #イベント会場詳細
    def show
      @event = Event.find(params[:id])
    end
    
    #イベント会場編集
    def edit
      @event = Event.find(params[:id])
    end
    
    #イベント会場登録
    def new
      @event = Event.new
    end
    
    #イベント会場登録処理
    def create
      @event = Event.new(event_params)
      if @event.save
        redirect_to events_path
      else
        render :new
      end
    end
    #イベント会場編集処理
    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        redirect_to event_path(@event)
      else
        render :edit
      end
    end
    
    #イベント会場一覧検索
    def search
      search = params[:search]
      word = params[:word]
      #全件検索
      if word.empty?
        @events = Event.page(params[:page]).reverse_order
      else
        @events = Event.looks(search, word).page(params[:page]).reverse_order
      end
      render :index
    end
    
    private
    def event_params
      params.require(:event).permit(:image, :eventname, :address, :siteurl, :comment)
    end
end

app/controllers/publics/favorites_controller.rb
class Publics::FavoritesController < ApplicationController
  #いいね追加処理
  def create
    @event = Event.find(params[:event_id])
    favorite = current_user.favorites.new(event_id: @event.id)
    favorite.save
    #redirect_to request.referer
  end

  #いいね解除処理
  def destroy
    @event = Event.find(params[:event_id])
    favorite = current_user.favorites.find_by(event_id: @event.id)
    favorite.destroy
    #redirect_to request.referer
  end
  private
  def favorite_params
    @event = Event.find(params[:event_id])
  end
end

app/controllers/publics/users/confirmations_controller.rb
# frozen_string_literal: true

class Publics::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/users/passwords_controller.rb
# frozen_string_literal: true

class Publics::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/users/registrations_controller.rb
# frozen_string_literal: true

class Publics::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  
  def require_no_authentication
    assert_is_devise_resource!
    return unless is_navigational_format?
    no_input = devise_mapping.no_input_strategies

    authenticated = if no_input.present?
      args = no_input.dup.push scope: resource_name
      warden.authenticate?(*args)
    else
      warden.authenticated?(resource_name)
    end

    if authenticated && resource = warden.user(resource_name)
      set_flash_message(:alert, 'already_authenticated', scope: 'devise.failure')
      redirect_to after_sign_in_path_for(resource)
    end
  end
end

app/controllers/publics/users/sessions_controller.rb
# frozen_string_literal: true

class Publics::Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/users/unlocks_controller.rb
# frozen_string_literal: true

class Publics::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/users_controller.rb
class Publics::UsersController < ApplicationController
  before_action :authenticate_user!
  #マイページ表示
  def show
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path
    end
  end
  #マイページ編集
  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path
    end
  end
  #マイページ更新
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path
    else
      render "edit"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image)
  end
  
end

app/helpers/admins/events_helper.rb
module Admins::EventsHelper
end

app/helpers/publics/events_helper.rb
module Publics::EventsHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/publics/events/_eventcomment.html.erb
<table>
  <% event.event_comments.each do |event_comment| %>
    <tr>
      <td class="breakWord">
        <%= event_comment.eventcomment %>
      </td>
      <% if event_comment.user == current_user %>
        <td class="d-button">
          <%= link_to "削除", event_event_comment_path(event, event_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_33853",remote: true %>
        </td>
      <% end %>
    </tr>  
  <% end %>
</table>

app/views/publics/events/_favorite.html.erb
<%# いいねの切り替えボタン %>
<% if event.favorited_by?(current_user) %>
  <p>
    <%= link_to event_favorites_path(event), method: :delete, remote: true do %><%# remote: trueを設定することで、ajaxを実装(今回は非同期通信)することが出来ます。 %>
     ♥<%= event.favorites.count %> いいね
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to event_favorites_path(event), method: :post, remote: true do %>
      ♡<%= event.favorites.count %> いいね
    <% end %>
  </p>
<% end %>

app/views/publics/events/edit.html.erb
<div class="container">
  <h1>イベント会場編集</h1>
  <% if @event.errors.any? %><!-- @eventのエラー情報チェック -->
    <div id="error_explanation">
      <!-- 下記は@eventのエラーの数をカウントして数値を出力 -->
      <h2><%= @event.errors.count %>件のエラーがあります。</h2>
      <!-- @eventのエラーメッセージを表示する -->
      <ul>
        <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div>
        <%= form_with model: @event, url: event_path(@event), method: :patch, local: true do |f| %>
        <div class="row">
            <div class="col-lg-3"><label class="lb">イベント会場画像：</label></div>
            <div class="col-lg-9"><%= f.attachment_field :image %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">イベント名：</label></div>
            <div class="col-lg-9"><%= f.text_field :eventname %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">住所：</label></div>
            <div class="col-lg-9"><%= f.text_area :address %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">サイトURL：</label></div>
            <div class="col-lg-9"><%= f.text_field :siteurl %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">イベント会場概要欄：</label></div>
            <div class="col-lg-9"><%= f.text_area :comment %></div>
        </div>
            <%= f.submit '変更を保存' %>
        <% end %>
    </div>
</div>    

app/views/publics/events/index.html.erb
<div class="container">
  <h1>イベント会場一覧</h1>
  
  <%= form_with url: search_events_path, method: :get, local: :true do |f| %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","start_match"], ["後方一致","back_match"], ["部分一致","partial_match"]]) %>
    <%= f.text_field :word %>
    <%= f.submit "検索" %>
    <!--%= submit_tag "Search", :title => nil %-->
  <% end %>
  
  <% if user_signed_in? %>
    <%= link_to "イベント会場登録", new_event_path , class: "btn btn-success" %><br />
  <% end %>
  
  <% @events.each do |event| %>
    <div class="d-inline-flex p-2 bd-highlight .col-6 .col-sm-3">
      <!--div class="p_index"-->
      <!--div class="eventall"-->
        <div class="p-2 bd-highlight">
        <div><%= attachment_image_tag event, :image, :fill, 300,300 %></div>
        <div class="fa-lg"><%= link_to event.eventname, event_path(event) %></div>
        <div><%= link_to event.siteurl, event.siteurl , target: :_blank, rel: "noopener noreferrer"%></div>
        <div class="favo">♥<%= event.favorites.count %> いいね</div>
        </div>
      <!--/div-->
    </div>
  <% end %>
  <%= paginate @events %>
</div>

app/views/publics/events/new.html.erb
<div class="container">
    <h1>イベント会場登録</h1>
    <% if @event.errors.any? %><!-- @eventのエラー情報チェック -->
      <div id="error_explanation">
        <!-- 下記は@eventのエラーの数をカウントして数値を出力 -->
        <h2><%= @event.errors.count %>件のエラーがあります。</h2>
        <!-- @eventのエラーメッセージを表示する -->
        <ul>
          <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
        <%= form_with model: @event, url: events_path, method: :post, local: true do |f| %>
        <div class="row">
            <div class="col-lg-3"><label class="lb">イベント会場画像：</label></div>
            <div class="col-lg-9"><%= f.attachment_field :image %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">イベント会場名：</label></div>
            <div class="col-lg-9"><%= f.text_field :eventname %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">住所：</label></div>
            <div class="col-lg-8"><%= f.text_area :address %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">サイトURL：</label></div>
            <div class="col-lg-9"><%= f.text_field :siteurl %></div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label class="lb">イベント会場概要欄：</label></div>
            <div class="col-lg-9"><%= f.text_area :comment %></div>
        </div>
        <%= f.submit '新規登録' %>
        <% end %>
    </div>
</div>    

app/views/publics/events/show.html.erb
<div class="container">
  <h1>イベント会場詳細</h1>
  <% if user_signed_in? %>
    <%= link_to '編集', edit_event_path(@event) , class: "btn btn-success" %>
  <% end %>
  <div class="row">
      <div class="col-lg-6">
        <div><%= attachment_image_tag @event, :image, :fill, 500,500, fallback: "no_image.jpg" %></div>
      </div>
      <div class="col-lg-6">
        <!--div class="p-2 bd-highlight"-->
        <div class="d-flex flex-column bd-highlight mb-3">
          <div class="p-2 bd-highlight">
            <label class="fa-lg">イベント会場名</label><br />
            <%= @event.eventname %>
          </div>
          <div class="p-2 bd-highlight">
            <label class="fa-lg">住所</label><br />
            <%= @event.address %>
          </div>
          <div class="p-2 bd-highlight">
            <label class="fa-lg">サイトURL</label><br />
            <%= link_to @event.siteurl, @event.siteurl, target: :_blank, rel: "noopener noreferrer" %>
          </div>
          <div class="p-2 bd-highlight">
            <label class="fa-lg">イベント会場概要欄</label><br />
            <%= @event.comment %>
          </div>
        </div>
        <!--/div-->
      </div>
  </div>
  
  <div class="row">
    <div class="col-lg-6">
      <div id="target"></div>
      <!--div id="address" value=<%#= @event.address %>></div-->
      <!--input id="address" value="<%#= @event.address %>"-->
      <!--住所-->
      <input id="address" type="hidden" value="<%= @event.address %>">
      <!--input type="button" value="検索" onclick="codeAddress()"-->
      <!--地図表示の範囲設定-->
      <style>#target {height: 500px;width: 500px;}</style>
      <!--GoogleMapApiで使用するAPIキーをマップURLに埋め込み-->
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY']%>&callback=initMap" async defer></script>
    </div>

    <div class="col-lg-6">
      <p class="fa-lg">いいね/コメント欄</p>
      <% if user_signed_in? %>
        <div id="favorite-<%= @event.id %>" class="favo">
          <%# いいねの部分テンプレートeventフォルダの_favorite.html.erbを参照 %>
          <%= render 'publics/events/favorite', event: @event %>
        </div>

        <div id="comments_area" class="scroll">
          <%= render 'publics/events/eventcomment', event: @event %>
        </div>
    
        <%= form_with model:@event_comment, url: event_event_comments_path(@event.id),local: false do |f| %> 
        <div class="form-group">
          <div class="field_with_errors">
            <label for="event_title">コメント</label>
          </div>
            <%= f.text_area :eventcomment %>
        </div>
        <div class="form-group">
          <%= f.submit '送信', class: "btn btn-success" %>
        </div>
        <% end %>
      <% else %>
        <div class="favo"><%= @event.favorites.count %> いいね</div>
        <%= render 'publics/events/eventcomment', event: @event %>
      <% end %>
    </div>
  </div>
</div>