config/routes.rb
Rails.application.routes.draw do

   #ネームスペースadminsのルート制御
  namespace :admins do
    resources :events
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #ネームスペースpublicsのルート制御
  #devise_for :users, controllers: {
  #  sessions: 'publics/users/sessions',
  #  registrations: 'publics/users/registrations',
  #  passwords: 'publics/users/passwords'
  #}
  

  #deviseはnamespaceで記載しない、階層を定義したらscopeで定義すること
  
  scope '/publics' do
     devise_for :users, controllers: {
      #各usersフォルダ内のコントローラ指定
      sessions: 'publics/users/sessions',
      registrations: 'publics/users/registrations',
      passwords: 'publics/users/passwords'
    }   
  end
  #scope module: :XXXXX 定義することでURLでXXXXXの部分をpath表示しなくてすむ
  scope module: :publics do
    resources :users, only:[:show,:edit,:update]
    
    resources :events, only:[:index, :show, :new, :edit, :create, :update] do
      collection do
        #新たにeventコントローラに検索(search)アクションを追加
        get 'search' => 'events#search'
      end
      resource :favorites, only:[:create, :destroy]
      resources :event_comments, only: [:create, :destroy]
    end
  end
  
  #devise_scope :user do
  #  get 'publics/users/sign_up', to: 'publics/users/registrations#new'
  #  post 'publics/users/sign_up', to: 'publics/users/registrations#create', as: :publics_user_registration
  #end
  #post 'publics/users' => 'publics/registrations#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to:'homes#top'
    
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/event.rb
class Event < ApplicationRecord
    #belongs_to :user
    
    attachment :image
    has_many :favorites, dependent: :destroy
    has_many :event_comments, dependent: :destroy
    validates :eventname, presence: true, length: { maximum: 20 }
    validates :address, presence: true, length: { maximum: 50 }
    validates :comment, presence: true, length: { maximum: 100 }
    validates :siteurl, presence: true, format: /\A#{URI::regexp(%w(http https))}\z/
    validates :image, presence: true
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
  def self.looks(searches, words)
    if searches == "perfect_match"
      @event = Event.where("eventname LIKE ?", "#{words}")
    elsif searches == "start_match"
      @event = Event.where("eventname LIKE ?", "#{words}%")
    elsif searches == "back_match"
      @event = Event.where("eventname LIKE ?", "%#{words}")
    else
      @event = Event.where("eventname LIKE ?", "%#{words}%")
    end
  end
end

app/controllers/admins/events_controller.rb
class Admins::EventsController < ApplicationController
    #イベント会場一覧
    def index
        #Events = Event.page(params[:page]) カミナリを使用する際はこちら
        @events = Event.all
    end
    #イベント会場登録
    def new
        @event = Event.new
    end
    #イベント会場詳細
    def show
        @event = Event.find(params[:id])
    end
    #イベント会場編集
    def edit
        @event = Event.find(params[:id])
    end
    #イベント会場登録処理
    def create
        @event = Event.new(event_params)
        @event.save
        redirect_to admins_event_path(@event)
    end
    #イベント会場編集処理
    def update
        @event = Event.find(params[:id])
        @event.update(event_params)
        redirect_to admins_event_path(@event)
    end
    #イベント会場削除処理
    def destroy
    
    end
    private
    def event_params
        params.require(:event).permit(:image, :eventname, :address, :siteurl, :comment)
    end
end

app/controllers/publics/events_controller.rb
class Publics::EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update]
    
    #イベント会場一覧
    def index
      @events = Event.page(params[:page]).reverse_order
    end
    
    #イベント会場詳細
    def show
      @event = Event.find(params[:id])
    end
    
    #イベント会場編集
    def edit
      @event = Event.find(params[:id])
    end
    
    #イベント会場登録
    def new
      @event = Event.new
    end
    
    #イベント会場登録処理
    def create
      @event = Event.new(event_params)
      if @event.save
        redirect_to events_path
      else
        render :new
      end
    end
    #イベント会場編集処理
    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        redirect_to event_path(@event)
      else
        render :edit
      end
    end
    
    #イベント会場一覧検索
    def search
      search = params[:search]
      word = params[:word]
      #全件検索
      if word.empty?
        @events = Event.page(params[:page]).reverse_order
      else
        @events = Event.looks(search, word).page(params[:page]).reverse_order
      end
      render :index
    end
    
    private
    def event_params
      params.require(:event).permit(:image, :eventname, :address, :siteurl, :comment)
    end
end

app/helpers/admins/events_helper.rb
module Admins::EventsHelper
end

app/helpers/publics/events_helper.rb
module Publics::EventsHelper
end

app/views/admins/events/edit.html.erb
<h1>イベント会場編集</h1>

<div>
    <%= form_with model: @event, url: admins_event_path(@event), method: :patch, local: true do |f| %>
    <div>
        <label>イベント会場画像：</label>
        <%= f.attachment_field :image %>
    </div>
    <div>
        <label>イベント名：</label>
        <%= f.text_field :eventname %>
    </div>
    <div>
        <label>住所</label>
        <%= f.text_area :address %>
    </div>
    <div>
        <label>サイトURL</label>
        <%= f.text_field :siteurl %>
    </div>
    <div>
        <label>イベント会場概要欄</label>
        <%= f.text_area :comment %>
    </div>
    
    <%= f.submit '変更を保存' %>
    <% end %>
</div>
    

app/views/admins/events/index.html.erb
<h1>イベント会場一覧</h1>

<%= link_to "新規登録", new_admins_event_path %>
<table>
    <tr>
        <th>イベント会場ID</th>
        <th>イベント会場名</th>
        <th>住所</th>
        <th>サイトURL</th>
    </tr>
    <% @events.each do |event| %>
    <tr>
        <td><%= event.id %></td>
        <td><%= link_to event.eventname, admins_event_path(event) %></td>
        <td><%= event.address %></td>
        <td><%= event.siteurl %></td>
    </tr>
    <% end %>
</table>

app/views/admins/events/new.html.erb
<h1>イベント会場登録</h1>

<div>
    <%= form_with model: @event, url: admins_events_path, method: :post, local: true do |f| %>
    <div>
        <label>イベント会場画像：</label>
        <%= f.attachment_field :image %>
    </div>
    <div>
        <label>イベント会場名：</label>
        <%= f.text_field :eventname %>
    </div>
    <div>
        <label>住所：</label>
        <%= f.text_area :address %>
    </div>
    <div>
        <label>サイトURL：</label>
        <%= f.text_field :siteurl %>
    </div>
    <div>
        <label>イベント会場概要欄：</label>
        <%= f.text_area :comment %>
    </div>
    <%= f.submit '新規登録' %>
    <% end %>
</div>
    

app/views/admins/events/show.html.erb
<h1>イベント会場詳細</h1>

<table>
    <tv>
        <div><%= attachment_image_tag(@event, :image, size: "100×100", fallback: "no_image.jpg") %></div>
        <div>
            <label>イベント会場名</label><%= @event.eventname %>
            <label>住所</label><%= @event.address %>
            <label>サイトURL</label><%= link_to @event.siteurl, @event.siteurl %>
            <label>イベント会場概要欄</label><%= @event.comment %>
        </div>
    </tr>
</table>
<%= link_to '編集', edit_admins_event_path(@event) %>