config/routes.rb
Rails.application.routes.draw do

   #ネームスペースadminsのルート制御
  namespace :admins do
    resources :events
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #ネームスペースpublicsのルート制御
  #devise_for :users, controllers: {
  #  sessions: 'publics/users/sessions',
  #  registrations: 'publics/users/registrations',
  #  passwords: 'publics/users/passwords'
  #}
  

  #deviseはnamespaceで記載しない、階層を定義したらscopeで定義すること
  
  scope '/publics' do
     devise_for :users, controllers: {
      #各usersフォルダ内のコントローラ指定
      sessions: 'publics/users/sessions',
      registrations: 'publics/users/registrations',
      passwords: 'publics/users/passwords'
    }   
  end
  #scope module: :XXXXX 定義することでURLでXXXXXの部分をpath表示しなくてすむ
  scope module: :publics do
    resources :users, only:[:show,:edit,:update]
    
    resources :events, only:[:index, :show, :new, :edit, :create, :update] do
      collection do
        #新たにeventコントローラに検索(search)アクションを追加
        get 'search' => 'events#search'
      end
      resource :favorites, only:[:create, :destroy]
      resources :event_comments, only: [:create, :destroy]
    end
  end
  
  #devise_scope :user do
  #  get 'publics/users/sign_up', to: 'publics/users/registrations#new'
  #  post 'publics/users/sign_up', to: 'publics/users/registrations#create', as: :publics_user_registration
  #end
  #post 'publics/users' => 'publics/registrations#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to:'homes#top'
    
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    #belongs_to :user
    
    attachment :image
    has_many :favorites, dependent: :destroy
    has_many :event_comments, dependent: :destroy
    validates :eventname, presence: true, length: { maximum: 20 }
    validates :address, presence: true, length: { maximum: 50 }
    validates :comment, presence: true, length: { maximum: 100 }
    validates :siteurl, presence: true, format: /\A#{URI::regexp(%w(http https))}\z/
    validates :image, presence: true
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
  def self.looks(searches, words)
    if searches == "perfect_match"
      @event = Event.where("eventname LIKE ?", "#{words}")
    elsif searches == "start_match"
      @event = Event.where("eventname LIKE ?", "#{words}%")
    elsif searches == "back_match"
      @event = Event.where("eventname LIKE ?", "%#{words}")
    else
      @event = Event.where("eventname LIKE ?", "%#{words}%")
    end
  end
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  
  validates :eventcomment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  #def after_sign_in_path_for(_resource)
  #  '/'
  #end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  # 確認画面を作成する場合はこのような記述になるかと思います。
  # newアクションから入力内容を受け取り、
  # 送信ボタンを押されたらcreateアクションを実行します。
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end
　
  # 入力内容に誤りがあった場合、
  # 入力内容を保持したまま前のページに戻るのが当たり前になっているかと思いますが、
  # backアクションを定義することで可能となります。
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # 実際に送信するアクションになります。
  # ここで初めて入力内容を保存します。
  # セキュリティーのためにも一定時間で入力内容の削除を行ってもいいかもしれません。
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  # 送信完了画面を使用する場合お使いください。
  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :phone_number, :subject, :message)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    favorite = current_user.favorites.new(event_id: event.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    event = Event.find(params[:event_id])
    favorite = current_user.favorites.find_by(event_id: event.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    #トップ画面処理
    def top
        @events = Event.all.order(id: :desc).limit(3)
    end
end

app/helpers/admins/events_helper.rb
module Admins::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/layouts/_foot.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
  <!--div class="container"-->
　<header>

    <!--div class="navbar_list"-->
      <ul class="navbar navbar-dark bg-warning">
        <div class="logo">
          <%= link_to root_path do %>
            <li><%= image_tag "event.png" ,class: "sized" %></li>
          <% end %>
        </div>
      　<% if user_signed_in? %>
          <li><%= "ようこそ、" %><%= current_user.name %><%= "さん！！" %><%= attachment_image_tag current_user, :profile_image, :fill, 50,50 %></li>

          <li><%= link_to ' マイページ', user_path(current_user), class: "btn btn-info" %></li>
          <li><%= link_to ' イベント会場一覧',events_path, class: "btn btn-info" %></li>
          <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-info" %></li>
        <% else %>

        <!--ログインしてないとき-->

          <li><!--%= link_to ' About', home_about_path %--></li>
          <li><%= link_to ' イベント会場一覧', events_path,  class: "btn btn-info"%></li>
          <li><%= link_to ' 新規登録', new_user_registration_path,  class: "btn btn-info"%></li>
          <li><%= link_to ' ログイン', new_user_session_path,  class: "btn btn-info"%></li>
        <% end %>
    　</ul>
　　<!--/div-->
　</header>
　<!--/div-->
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PfEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <!--div class="container"-->
    <body>
      <div class="jumbotron jumbotron-fluid">
        <%= render 'layouts/head' %>
        <%= yield %>
        <%= render 'layouts/foot' %>
      </div>
    </body>
  <!--/div-->
</html>